#!/usr/bin/env bash
# Generate a ready-to-run .env for a self-hosted CrawlSEO deployment.
# Secrets are generated locally; Google OAuth credentials are left as
# placeholders because they can only come from the Google Cloud Console.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo "refusing to overwrite existing .env — edit it by hand or delete it first" >&2
  exit 1
fi

rand() { openssl rand -hex 32; }

APP_SECRET=$(rand)
NEXTAUTH_SECRET=$(rand)
POSTGRES_PASSWORD=$(openssl rand -hex 16)
BASE_URL=${BASE_URL:-http://localhost:3000}

cat > .env <<ENV
# Generated by scripts/bootstrap.sh — keep this file out of git.

# ---- database (matches docker-compose.yml) ----
POSTGRES_USER=crawlseo
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=crawlseo
DATABASE_URL=postgresql://crawlseo:${POSTGRES_PASSWORD}@db:5432/crawlseo

# ---- secrets ----
APP_SECRET=${APP_SECRET}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# ---- auth ----
NEXTAUTH_URL=${BASE_URL}
AUTH_TRUST_HOST=true

# ---- Google OAuth: fill these in, see SETUP.md ----
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ---- optional: raises the Core Web Vitals quota ----
# GOOGLE_PAGESPEED_KEY=

# ---- optional: close registration once your account exists ----
# DISABLE_REGISTRATION=true
ENV

chmod 600 .env

# The MCP server and any host-run tooling talk to Postgres over the port that
# Compose publishes, not over the container network, so they need their own
# DATABASE_URL.
cat > .env.local <<ENV
# Generated by scripts/bootstrap.sh — host-side counterpart of .env.
DATABASE_URL=postgresql://crawlseo:${POSTGRES_PASSWORD}@localhost:5432/crawlseo
ENV
chmod 600 .env.local

echo "wrote .env and .env.local with generated secrets"
echo "next: add GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET (see SETUP.md), then: docker compose up -d"
